### ISSUE TITLE
Amazon Route 53 now supports CAA records

### ISSUE THREAD

**Issue by WToorenburghEasyMarkit** [SSLMate/caa_helper#61]
Checking the Route 53 dashboard this afternoon, I saw that the CAA record type is now available:
![image](https://user-images.githubusercontent.com/29389028/29539177-ac7ab478-867d-11e7-878a-e45d59a8773d.png)

**Comment by AGWA** [comment]
It's official! https://forums.aws.amazon.com/ann.jspa?annID=4799

**Comment by WToorenburghEasyMarkit** [comment]
Hah, I guess I managed to post here before they pushed the official announcement

**Comment by Ayesh** [comment]
Finally!

**Comment by bacoboy** [comment]
Anybody know the proper domain to use in the CCA record for AWS ACM?

**Comment by AGWA** [comment]
@bacoboy Amazon uses `amazon.com`

**Comment by bacoboy** [comment]
Inspection of an ACM issued cert made me think it would be `amazontrust.com` based on the CRL domain:

<img width="425" alt="acm" src="https://user-images.githubusercontent.com/874597/29936716-d213033e-8e48-11e7-89eb-e2600e4f6040.png">

However, I opened a ticket with AWS and they point out the [buried NOTE in their docs](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/ResourceRecordTypes.html#CAAFormat)

> AWS Certificate Manager (ACM) currently doesn't support CAA records.

After talking with our security guy it turns out this doesn't really matter as this record is to keep OTHER SSL providers from issuing certs for your domain.  For instance Comodo won't issue a cert unless the CCA is set to their domain.  This lack of support really means you can't use ACM to request a cert for another domain -- but really ACM/AWS has their own [mechanism for showing ownership](http://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate.html).
